---
apiVersion: "batch/v1"
kind: "CronJob"
spec:
  concurrencyPolicy: "Forbid"
  suspend: false
  successfulJobsHistoryLimit: 20
  schedule: "*/5 * * * *"
  failedJobsHistoryLimit: 20
  jobTemplate:
  - metadata:
      annotations: {}
    spec:
      ttlSecondsAfterFinished: 1200
      backoffLimit: 6
      parallelism: 1
      completions: 1
      template:
        metadata:
          annotations: {}
          labels:
            app.kubernetes.io/component: "cronjob.bcl2fastq-dryrun"
        spec:
          restartPolicy: "OnFailure"
          terminationGracePeriodSeconds: 30
          nodeSelector: {}
          volumes:
          - name: "bcl2fastq"
            nfs:
              path: "/"
              server: "fs-0702fd3f2daf48ffd.efs.us-west-1.amazonaws.com"
              readOnly: false
          containers:
          - name: "bcl2fastq"
            image: "066843452437.dkr.ecr.us-west-1.amazonaws.com/test-qa-repository:qa_test"
            command: ["bcl2fastq.sh"]
            imagePullPolicy: "Always"
            volumeMounts:
            - name: "bcl2fastq"
              readOnly: false
              mountPath: "/bcl2fastq"
          securityContext:
            runAsUser: 0
metadata:
  annotations: {}
  name: "bcl2fastq"
  labels:
    app.kubernetes.io/name: "bcl2fastq"
    app.kubernetes.io/component: "cronjob.bcl2fastq-dryrun"
